### ISSUE TITLE
Can't install 1.3.0 version

### ISSUE THREAD

**Issue by Carlos-Rodero** [rbardaji/mooda#4]
#### Title
Can't update to 1.3.0 version

#### Steps to reproduce 
1. In your Python environment terminal, type:
- pip install mooda==1.3.0 
or
- pip install mooda --update

#### Current behaviour 
It does not install this version of package

#### Expected behaviour 
Appear mooda==1.3.0 when you try to see your requirements

#### Relevant logs and/or screenshots (optional)
ERROR: Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from mooda) (from versions: none)
ERROR: No matching distribution found for pkg-resources==0.0.0 (from mooda)

#### Reported by
Carlos Rodero

**Comment by rbardaji** [comment]
Hi Carlos,

Thanks to report the issue.

I deleted the ```pkg-resources==0.0.0``` from requeriments.txt and uploaded a new verion on Pypi.
Could you try to update your version again?

**Comment by Carlos-Rodero** [comment]
Hi Raul,

It works perfectly.
Thanks for resolving this issue

**Comment by matthiasbirkich** [comment]
Dear Raul,

I am very exited about your work on KduPRO! We are dealing with light measurements in the tropics...
Thank you very much for the development of the KduPro and the analysis software for python.
I build one KduPRO for our divers and I got the first dataset, but there is a problem during installation of your mooda package.
I have installed all packages according to the requirements.txt under Python 3.8.1 and I tryed to run "main.py"
It asked for the package of mooda.
When I try to install mooda-1.13.1 following error during netcdf4 installation is displayed:
Collecting netCDF4>=1.5.3 (from mooda)
  Using cached netcdf4-1.7.2.tar.gz (835 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  hdf5 headers not found

Do you have any clou, how I can solve this error?

Best regards
Matthias
